### ISSUE TITLE
Webstart fails with nullpointer Exception

### ISSUE THREAD

**Issue by vkotkas** [CoCoViLa/CoCoViLa#109]
vahur@pontu:~/tmp> javaws http://www.cs.ioc.ee/cocovila/webstart/CoCoViLa.jnlp
Codebase matches codebase manifest attribute, and  application is signed. Continuing. See: http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/security/no_redeploy.html for details.
Application title was not found in manifest. Check with application vendor
Application title was not found in manifest. Check with application vendor
Application title was not found in manifest. Check with application vendor
Application title was not found in manifest. Check with application vendor
16:48:36.664 [AWT-EventQueue-1] INFO  ee.ioc.cs.vsle.editor.Editor - Java Version: 1.8.0_40
16:48:36.668 [AWT-EventQueue-1] INFO  ee.ioc.cs.vsle.editor.Editor - Working directory: /home/vahur/CoCoViLa/
Exception in thread "AWT-EventQueue-1" java.lang.NullPointerException
        at ee.ioc.cs.vsle.util.SystemUtils.unpackPackages(SystemUtils.java:24)
        at ee.ioc.cs.vsle.editor.Editor.extractPackages(Editor.java:781)
        at ee.ioc.cs.vsle.editor.Editor.createAndInitGUI(Editor.java:695)
        at ee.ioc.cs.vsle.editor.Editor$7.run(Editor.java:641)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:702)
        at java.awt.EventQueue$3.run(EventQueue.java:696)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by MastaP** [comment]
Hmm....what if you choose not to extract packages?

**Comment by vkotkas** [comment]
Having the packages already there causes no NullPointerExc..., the same for choosing not to extract packages.
